<a href="https://colab.research.google.com/github/ArkhamCorrupt/ArkhamCorrupt/blob/main/Tensors_Video_Demos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch Tutorial #2

In [2]:
import torch

x = torch.empty(3)#like a 1dimensional vector with 3 elements
print(x)

tensor([1.1933e-34, 0.0000e+00, 1.1933e-34])


In [5]:
import torch

x = torch.empty(2, 3)#like a 2 dimensional vector with 3 elements
print(x)

tensor([[-5.5765e-21,  4.5598e-41,  1.1969e-34],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])


In [8]:
import torch

x = torch.rand(2,2)#creates a random 2 by 2 tensor you can also say torch.ones or torch.zeros to make them ones or zeros
print(x)

tensor([[0.1592, 0.9078],
        [0.1153, 0.3356]])


In [10]:
import torch

x = torch.ones(2,2, dtype=torch.int)
print(x.size())#this can take a look at the size of the tensor

torch.Size([2, 2])


In [11]:
import torch

x = torch.tensor([2.5, 0.1, 5.7 ])#this makes a list
print(x)#this prints the list 

tensor([2.5000, 0.1000, 5.7000])


In [13]:
import torch

x = torch.rand(5,3)#makes a 5 dimensional tensor of 3 values
print(x)
print(x[:,0])#this would be the first column of all the rows
print(x[0,:])#this would be the first row of all the columns
print(x[1,1])#this would be the second column, second row,second spot




tensor([[0.5005, 0.4796, 0.9684],
        [0.1577, 0.2170, 0.0753],
        [0.8683, 0.1833, 0.4663],
        [0.8609, 0.1278, 0.2586],
        [0.0767, 0.7240, 0.7561]])
tensor([0.5005, 0.1577, 0.8683, 0.8609, 0.0767])
tensor([0.5005, 0.4796, 0.9684])
tensor(0.2170)


In [15]:
import torch

x = torch.rand(4,4)
print(x)
y = x.view(-1,8)
print(y.size())

tensor([[0.0893, 0.8888, 0.1482, 0.9330],
        [0.5225, 0.7813, 0.1180, 0.5014],
        [0.5320, 0.1974, 0.7525, 0.1019],
        [0.4266, 0.2804, 0.7656, 0.7999]])
torch.Size([2, 8])
tensor([[0.4310, 0.8562, 0.9322, 0.7497],
        [0.2537, 0.8015, 0.6622, 0.7722],
        [0.8626, 0.6522, 0.4562, 0.7932],
        [0.5100, 0.6554, 0.6188, 0.4404]])
torch.Size([2, 8])


In [18]:
import numpy as np
import torch

a = torch.ones(5)
print(a)
b = a.numpy()#converts a into a numpy array
print(b)

a.add_(1)
print(a)
print(b)


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
import torch

a = np.ones(5)
print(a)
b = torch.from_numpy(a)#converts a numpy array into a tensor
print(b)

a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
import torch
import numpy as np
x = torch.ones(5, requires_grad = True)#reminds it that it needs to calculate gradience
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


PyTorch Tutorial #3: Autograd Gradient Computation

In [7]:
import torch

x = torch.randn(3, requires_grad = True)#tensor with 3 random values
print(x)

y = x + 2
print(y)
z = y*y*2
z = z.mean()
print(z)

v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float32)
z.backward() #calculates the gradient of z, dz/dx or z in respect to x
print(x.grad)

tensor([ 0.0973,  0.4605, -2.2168], requires_grad=True)
tensor([ 2.0973,  2.4605, -0.2168], grad_fn=<AddBackward0>)
tensor(6.9999, grad_fn=<MeanBackward0>)
tensor([ 2.7965,  3.2807, -0.2891])


In [8]:
import torch

x = torch.randn(3, requires_grad=True)
print(x)
#To stop PyTorch from creating this gradient function use these 3 ways:
#x.requires_grad_(False)
#x.detach()
#with torch.no_grad():

x.requires_grad_(False)
y= x.detach()
print(y)

tensor([-0.7602, -1.0751,  0.5233], requires_grad=True)
tensor([-0.7602, -1.0751,  0.5233])


In [13]:
import torch

weights = torch.ones(4, requires_grad=True)

for epoch in range(4):
  model_output = (weights*3).sum()

  model_output.backward() #this gives us the gradient

  print(weights.grad)

  weights.grad.zero_()#this puts all the values back at 3 instead of 3,6,9,12 that you would see if you comment out this line
  #you could also call that emptying the gradients

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [14]:
import torch

weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)  #our lr here is our learning rate
optimizer.step()
optimizer.zero_grad()


TypeError: ignored

In [ ]:
import torch

weights = torch.ones(4, requires_grad=True)
#whenever we want to calculate the gradience we must specify that it requires grad=True

z.backward()
weights.grad.zero_()

Chapter 4: Backpropagation

In [17]:
#backprop has 3 steps:   1.Forward Pass: Compute the loss      2. Compute Local Gradients      3. Backward Pass: Compute dLoss/dWeights using the Chain Rule
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)

weight= torch.tensor(1.0, requires_grad=True)

#Computing the forward pass and computing the loss
y_hat = weight * x
loss = (y_hat - y)**2

print(loss)

#backward pass
loss.backward()
print(weight.grad)

#Update the weights
#next forward and backwards pass



tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


Chapter 5: Gradient Descent using Autograd

In [33]:
import numpy as np

# f = w * x

# f = 2 * x
x = np.array([1, 2, 3, 4], dtype=np.float32)
y = np.array([2, 4, 6, 8], dtype=np.float32)

w = 0.0

##### model prediction ######
def forward(x):
    return w * x

# loss = Mean Squared Error or MSE
def loss(y, y_predicted):
    return ((y - y_predicted) ** 2).mean()

# gradient
# MSE = 1/N * (w*x - y)**2
# dj/dw = 1/N * 2x * (w*x - y)
def gradient(x, y, y_predicted):
    return np.dot(2 * x, y_predicted - y).mean()

print(f'prediction before training: f(5) = {forward(5):.3f}')

##### Training ####
learning_rate = 0.01
num_of_iterations = 10

for epoch in range(num_of_iterations):
    # prediction = forward pass
    y_pred = forward(x)

    # loss
    l = loss(y, y_pred)

    # gradients
    dw = gradient(x, y, y_pred)

    # update weights
    w -= learning_rate * dw

    if epoch % 1 == 0:
        print(f'epoch {epoch+1}: weight = {w:.3f}, loss = {l:.8f}')

print(f'prediction AFTER training: f(5) = {forward(5):.3f}')

prediction before training: f(5) = 0.000
epoch 1: weight = 1.200, loss = 30.00000000
epoch 2: weight = 1.680, loss = 4.79999924
epoch 3: weight = 1.872, loss = 0.76800019
epoch 4: weight = 1.949, loss = 0.12288000
epoch 5: weight = 1.980, loss = 0.01966083
epoch 6: weight = 1.992, loss = 0.00314574
epoch 7: weight = 1.997, loss = 0.00050331
epoch 8: weight = 1.999, loss = 0.00008053
epoch 9: weight = 1.999, loss = 0.00001288
epoch 10: weight = 2.000, loss = 0.00000206
prediction AFTER training: f(5) = 9.999


In [38]:
import torch

# f = w * x

# f = 2 * x
x = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
y = torch.tensor([2, 4, 6, 8], dtype=torch.float32)

w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)

##### model prediction ######
def forward(x):
    return w * x

# loss = Mean Squared Error or MSE
def loss(y, y_predicted):
    return ((y - y_predicted) ** 2).mean()

print(f'prediction before training: f(5) = {forward(5):.3f}')

##### Training ####
learning_rate = 0.01
num_of_iterations = 100   #number of steps

for epoch in range(num_of_iterations):
    # prediction = forward pass
    y_pred = forward(x)

    # loss
    l = loss(y, y_pred)

    # gradients = backward pass
    l.backward() #calculates the gradients of our loss in respect to w 

    # update weights
    with torch.no_grad():
      w -= learning_rate * w.grad
  #zero gradients
    w.grad.zero_()

    if epoch % 10 == 0:#shows every 1 step, if we change the number after the % it shows after that many steps
        print(f'epoch {epoch+1}: weight = {w:.3f}, loss = {l:.8f}')

print(f'prediction AFTER training: f(5) = {forward(5):.3f}')

prediction before training: f(5) = 0.000
epoch 1: weight = 0.300, loss = 30.00000000
epoch 11: weight = 1.665, loss = 1.16278565
epoch 21: weight = 1.934, loss = 0.04506890
epoch 31: weight = 1.987, loss = 0.00174685
epoch 41: weight = 1.997, loss = 0.00006770
epoch 51: weight = 1.999, loss = 0.00000262
epoch 61: weight = 2.000, loss = 0.00000010
epoch 71: weight = 2.000, loss = 0.00000000
epoch 81: weight = 2.000, loss = 0.00000000
epoch 91: weight = 2.000, loss = 0.00000000
prediction AFTER training: f(5) = 10.000


Tutorial 6: Training Pipeline: Model/Loss/Optimizer